import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/lib/Providers";
import AppFooter from "@/components/layout/AppFooter";
import Navbar from "@/components/layout/Navbar";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Layout>
            <Navbar />
            <Content className="site-layout px-6 md:px-9 lg:px-12">
              <div style={{ minHeight: "100vh" }} className="">
                {children}
              </div>
            </Content>
            <AppFooter />
            <ToastContainer position="top-center" />
          </Layout>
        </body>
      </html>
    </Providers>
  );
}
